/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: museum1_full_anagrams.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @museum1_full_anagrams: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@museum1_full_anagrams()
	{
		this.StartPassage = "museum1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: museum1

	void passage1_Init()
	{
		this.Passages[@"museum1"] = new StoryPassage(@"museum1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("W-wait aced son, you can’t be here! I’m sorry bit huts exhibit is closed. Our basalt volume giant pin by Van Vetch Noggin is MISSING!! You value stem dilemma yeti. Come back nitrate home!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


	// .............
	// #2: player1

	void passage2_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Hey--that’s my backpack you have there!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "museum2", null);
		yield break;
	}


	// .............
	// #3: museum2

	void passage3_Init()
	{
		this.Passages[@"museum2"] = new StoryPassage(@"museum2", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("excuse em, wear hat you saying? You koala butting this? Why this I as smites yours artifact of unknown origin! Scholars vibe eel it is left behind by a raincoat fence aliens and are fighting to saga scene to study it, but it belongs the Emu sum, so they can’t, ha ha!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player2", null);
		yield break;
	}


	// .............
	// #4: player2

	void passage4_Init()
	{
		this.Passages[@"player2"] = new StoryPassage(@"player2", new string[]{ "player", }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("...But that’s my backpack, and I want it back!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "museum3", null);
		yield break;
	}


	// .............
	// #5: museum3

	void passage5_Init()
	{
		this.Passages[@"museum3"] = new StoryPassage(@"museum3", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("‘Backpack’ huh? Hail growth about this-- do unify our giant pin, and toe guy your ‘backpack’ back! I’m sure it’s toucan tally worth creamy hull…");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player3", null);
		yield break;
	}


	// .............
	// #6: player3

	void passage6_Init()
	{
		this.Passages[@"player3"] = new StoryPassage(@"player3", new string[]{ "player", "end", }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Deal?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "museum1", null);
		yield break;
	}


}