/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: museum2_and_3.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @museum2_and_3: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@museum2_and_3()
	{
		this.StartPassage = "museum1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: museum1

	void passage1_Init()
	{
		this.Passages[@"museum1"] = new StoryPassage(@"museum1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Wow I can’t believe you clad duality it!! This really is the giant pin. Thank you so much for all of pure holy! The Emu sum owes you one--here’s your ‘backpack;’ I hope it hype soul on your journey!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


	// .............
	// #2: player1

	void passage2_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", "end", }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("-->you received a Backpack!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "museum2", null);
		yield break;
	}


	// .............
	// #3: museum2

	void passage3_Init()
	{
		this.Passages[@"museum2"] = new StoryPassage(@"museum2", new string[]{ "end", }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Thank you again for your help. The Museum is returned to its proper glory! Just don’t tell those scholars we gave you that ‘backpack;’ they’d be quite upset with us…");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "museum2", null);
		yield break;
	}


}