/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: museum2.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @museum2: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@museum2()
	{
		this.StartPassage = "museum1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: museum1

	void passage1_Init()
	{
		this.Passages[@"museum1"] = new StoryPassage(@"museum1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("W-wait ACED SON, you can’t be here! I’m sorry BIT HUTS exhibit is closed. Our most valuable ~GIANT PIN~ by VAN VETCH NOGGIN is missing!!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "museum2", null);
		yield break;
	}


	// .............
	// #2: player1

	void passage2_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Hey--that’s my backpack you have there!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "museum3", null);
		yield break;
	}


	// .............
	// #3: museum3

	void passage3_Init()
	{
		this.Passages[@"museum3"] = new StoryPassage(@"museum3", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Excuse EM, WEAR HAT you saying? You KOALA BUTTING this? Why this I AS SMITES YOURS artifact of unknown origin! ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "museum4", null);
		yield break;
	}


	// .............
	// #4: player2

	void passage4_Init()
	{
		this.Passages[@"player2"] = new StoryPassage(@"player2", new string[]{ "player", }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("...But that’s my backpack, and I want it back!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "museum5", null);
		yield break;
	}


	// .............
	// #5: museum5

	void passage5_Init()
	{
		this.Passages[@"museum5"] = new StoryPassage(@"museum5", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("‘Backpack’ huh? HAIL GROWTH about this--DO UNIFY our ~GIANT PIN~, and you get your ‘backpack’ back! I’m sure it’s TOUCAN TALLY worth much really…");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player3", null);
		yield break;
	}


	// .............
	// #6: player3

	void passage6_Init()
	{
		this.Passages[@"player3"] = new StoryPassage(@"player3", new string[]{ "player", "end", }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Deal?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "museum1", null);
		yield break;
	}


	// .............
	// #7: museum2

	void passage7_Init()
	{
		this.Passages[@"museum2"] = new StoryPassage(@"museum2", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("You must leave DILEMMA YETI. Come back NITRATE HOME!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


	// .............
	// #8: museum4

	void passage8_Init()
	{
		this.Passages[@"museum4"] = new StoryPassage(@"museum4", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("Scholars VIBE EEL it is left behind by a RAINCOAT FENCE aliens and are fighting to SAGA SCENIC to study it, but it belongs the EMU SUM, so they can’t, ha ha!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player2", null);
		yield break;
	}


}