/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: bartender2.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @bartender2: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@bartender2()
	{
		this.StartPassage = "bar1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: bar1

	void passage1_Init()
	{
		this.Passages[@"bar1"] = new StoryPassage(@"bar1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("hmm you certainly don’t seem to be from around these parts… ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "bar2", null);
		yield break;
	}


	// .............
	// #2: bar2

	void passage2_Init()
	{
		this.Passages[@"bar2"] = new StoryPassage(@"bar2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Well, I suppose it doesn't matter, a customer is a customer, even a strange lookin' one like you.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "bar3", null);
		yield break;
	}


	// .............
	// #3: player1

	void passage3_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("uh...");
		yield return lineBreak();
		yield return link("space", "bar4", null);
		yield break;
	}


	// .............
	// #4: bar3

	void passage4_Init()
	{
		this.Passages[@"bar3"] = new StoryPassage(@"bar3", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("So. What'll it be?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


	// .............
	// #5: bar4

	void passage5_Init()
	{
		this.Passages[@"bar4"] = new StoryPassage(@"bar4", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Pick your poison.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player3", null);
		yield break;
	}


	// .............
	// #6: player3

	void passage6_Init()
	{
		this.Passages[@"player3"] = new StoryPassage(@"player3", new string[]{ "player", }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Do you have any PA ICE JULEP?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "bar5", null);
		yield break;
	}


	// .............
	// #7: bar5

	void passage7_Init()
	{
		this.Passages[@"bar5"] = new StoryPassage(@"bar5", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("of course, I've got the finest PA ICE JULEP in town.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "bar6", null);
		yield break;
	}


	// .............
	// #8: bar6

	void passage8_Init()
	{
		this.Passages[@"bar6"] = new StoryPassage(@"bar6", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("that'll be 4 ~SONIC~.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player4", null);
		yield break;
	}


	// .............
	// #9: player4

	void passage9_Init()
	{
		this.Passages[@"player4"] = new StoryPassage(@"player4", new string[]{ "player", }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player5", null);
		yield break;
	}


	// .............
	// #10: player5

	void passage10_Init()
	{
		this.Passages[@"player5"] = new StoryPassage(@"player5", new string[]{ "player", }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("can you take an I.O.U.?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "bar7", null);
		yield break;
	}


	// .............
	// #11: bar7

	void passage11_Init()
	{
		this.Passages[@"bar7"] = new StoryPassage(@"bar7", new string[]{ "end", }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("Get out.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "bar1", null);
		yield break;
	}


}