/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: broom_guy3.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @broom_guy3: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@broom_guy3()
	{
		this.StartPassage = "broom1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: broom1

	void passage1_Init()
	{
		this.Passages[@"broom1"] = new StoryPassage(@"broom1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Where's my ~APPLE JUICE~?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


	// .............
	// #2: broom2

	void passage2_Init()
	{
		this.Passages[@"broom2"] = new StoryPassage(@"broom2", new string[]{ "end", }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("Less yappin' more ~APPLE JUICE~ gatherin'!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom1", null);
		yield break;
	}


	// .............
	// #3: player1

	void passage3_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("I'm still on the lookout.  I'm starting to feel like I need a drink myself.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom2", null);
		yield break;
	}


}