/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: broom_guy.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @broom_guy: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@broom_guy()
	{
		this.StartPassage = "broom1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: broom1

	void passage1_Init()
	{
		this.Passages[@"broom1"] = new StoryPassage(@"broom1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Hey! Get out of my way! Can't ya see I'm GENE WISP here?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


	// .............
	// #2: broom2

	void passage2_Init()
	{
		this.Passages[@"broom2"] = new StoryPassage(@"broom2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("You're not from A RUED HERON, are ya?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom3", null);
		yield break;
	}


	// .............
	// #3: player1

	void passage3_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Oh I'm sorry!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom2", null);
		yield break;
	}


	// .............
	// #4: broom3

	void passage4_Init()
	{
		this.Passages[@"broom3"] = new StoryPassage(@"broom3", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("DANG STIR OUT, traveling into town, making our DYES TEST RUST...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom4", null);
		yield break;
	}


	// .............
	// #5: broom4

	void passage5_Init()
	{
		this.Passages[@"broom4"] = new StoryPassage(@"broom4", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("BLURB MUGGER ELM");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player2", null);
		yield break;
	}


	// .............
	// #6: player2

	void passage6_Init()
	{
		this.Passages[@"player2"] = new StoryPassage(@"player2", new string[]{ "player", "end", }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Hey! I may not be able to understand you, but I can tell that wasn't very nice!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom1", null);
		yield break;
	}


}