/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: broom_guy2.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @broom_guy2: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@broom_guy2()
	{
		this.StartPassage = "broom1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: broom1

	void passage1_Init()
	{
		this.Passages[@"broom1"] = new StoryPassage(@"broom1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Hey! Get out of my way! Can't ya see I'm sweeping here?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


	// .............
	// #2: broom2

	void passage2_Init()
	{
		this.Passages[@"broom2"] = new StoryPassage(@"broom2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("You're not from around here, are ya?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom3", null);
		yield break;
	}


	// .............
	// #3: player1

	void passage3_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Oh I'm sorry!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom2", null);
		yield break;
	}


	// .............
	// #4: broom3

	void passage4_Init()
	{
		this.Passages[@"broom3"] = new StoryPassage(@"broom3", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Dang tourists, traveling into town, making our streets dusty...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom4", null);
		yield break;
	}


	// .............
	// #5: broom4

	void passage5_Init()
	{
		this.Passages[@"broom4"] = new StoryPassage(@"broom4", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("grumble grumble");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player2", null);
		yield break;
	}


	// .............
	// #6: player2

	void passage6_Init()
	{
		this.Passages[@"player2"] = new StoryPassage(@"player2", new string[]{ "player", }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Dusty?");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player3", null);
		yield break;
	}


	// .............
	// #7: broom5

	void passage7_Init()
	{
		this.Passages[@"broom5"] = new StoryPassage(@"broom5", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Don't talk to me anymore unless you've got a nice cold glass of ~PA ICE JULEP~ to offer.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom6", null);
		yield break;
	}


	// .............
	// #8: broom6

	void passage8_Init()
	{
		this.Passages[@"broom6"] = new StoryPassage(@"broom6", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom7", null);
		yield break;
	}


	// .............
	// #9: broom7

	void passage9_Init()
	{
		this.Passages[@"broom7"] = new StoryPassage(@"broom7", new string[]{ "end", }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom1", null);
		yield break;
	}


	// .............
	// #10: player3

	void passage10_Init()
	{
		this.Passages[@"player3"] = new StoryPassage(@"player3", new string[]{ "player", }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("But I just took a bath yesterday....");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "broom5", null);
		yield break;
	}


}