/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: tutorial3.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @tutorial3: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@tutorial3()
	{
		this.StartPassage = "player1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: player1

	void passage1_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Hey, have you seen my backpack? I think I might’ve left it around here...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "npc1", null);
		yield break;
	}


	// .............
	// #2: npc1

	void passage2_Init()
	{
		this.Passages[@"npc1"] = new StoryPassage(@"npc1", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("fdakl;fdjkla;fjdkla;");
		yield return lineBreak();
		yield return link("space", "player2", null);
		yield break;
	}


	// .............
	// #3: player2

	void passage3_Init()
	{
		this.Passages[@"player2"] = new StoryPassage(@"player2", new string[]{ "player", }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Oh no! I don’t have my travel guides! I can’t understand a word he’s saying without my guides, and I left them in my backpack…");
		yield return lineBreak();
		yield return link("space", "player3", null);
		yield break;
	}


	// .............
	// #4: player3

	void passage4_Init()
	{
		this.Passages[@"player3"] = new StoryPassage(@"player3", new string[]{ "player", "end", }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("It looks as though my backpack isn’t here anyways, so I should go into town and look for it there; someone else might’ve picked it up…");
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


}