/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: tutorial2.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @tutorial2: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@tutorial2()
	{
		this.StartPassage = "player1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: player1

	void passage1_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Oh no! Where's my backpack?  I must have left it back there.");
		yield return lineBreak();
		yield return link("space", "player2", null);
		yield break;
	}


	// .............
	// #2: player2

	void passage2_Init()
	{
		this.Passages[@"player2"] = new StoryPassage(@"player2", new string[]{ "player", "end", }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("I should go back and ask that nice person if he’s seen it.");
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


}