/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: dog2.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @dog2: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@dog2()
	{
		this.StartPassage = "dog1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: dog1

	void passage1_Init()
	{
		this.Passages[@"dog1"] = new StoryPassage(@"dog1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("WOOF WOOF!");
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


	// .............
	// #2: player1

	void passage2_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("wow, you are really excited today.");
		yield return lineBreak();
		yield return link("space", "dog2", null);
		yield break;
	}


	// .............
	// #3: dog2

	void passage3_Init()
	{
		this.Passages[@"dog2"] = new StoryPassage(@"dog2", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		using (Group("em", true)) {
			yield return text("sniff");
		}
		yield return text(" ");
		using (Group("em", true)) {
			yield return text("sniff");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player2", null);
		yield break;
	}


	// .............
	// #4: player2

	void passage4_Init()
	{
		this.Passages[@"player2"] = new StoryPassage(@"player2", new string[]{ "player", }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Did you want this Art Spy in my pocket?");
		yield return lineBreak();
		yield return link("space", "dog4", null);
		yield break;
	}


	// .............
	// #5: player3

	void passage5_Init()
	{
		this.Passages[@"player3"] = new StoryPassage(@"player3", new string[]{ "player", }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("Ok.  Then... How about a trick for me?");
		yield return lineBreak();
		yield return link("space", "player4", null);
		yield break;
	}


	// .............
	// #6: dog4

	void passage6_Init()
	{
		this.Passages[@"dog4"] = new StoryPassage(@"dog4", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("BARK BARK BARK BARK BARK");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player3", null);
		yield break;
	}


	// .............
	// #7: player4

	void passage7_Init()
	{
		this.Passages[@"player4"] = new StoryPassage(@"player4", new string[]{ "player", }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text("Fetch.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "dog5", null);
		yield break;
	}


	// .............
	// #8: dog5

	void passage8_Init()
	{
		this.Passages[@"dog5"] = new StoryPassage(@"dog5", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text("...");
		yield return lineBreak();
		yield return link("space", "player5", null);
		yield break;
	}


	// .............
	// #9: player5

	void passage9_Init()
	{
		this.Passages[@"player5"] = new StoryPassage(@"player5", new string[]{ "player", }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text("Roll over.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "dog6", null);
		yield break;
	}


	// .............
	// #10: dog6

	void passage10_Init()
	{
		this.Passages[@"dog6"] = new StoryPassage(@"dog6", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text("...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player7", null);
		yield break;
	}


	// .............
	// #11: player7

	void passage11_Init()
	{
		this.Passages[@"player7"] = new StoryPassage(@"player7", new string[]{ "player", }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text("sit.");
		yield return lineBreak();
		yield return link("space", "dog7", null);
		yield break;
	}


	// .............
	// #12: dog7

	void passage12_Init()
	{
		this.Passages[@"dog7"] = new StoryPassage(@"dog7", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text("...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player8", null);
		yield break;
	}


	// .............
	// #13: player8

	void passage13_Init()
	{
		this.Passages[@"player8"] = new StoryPassage(@"player8", new string[]{ "player", }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text("Oh! I got it! Do NOTHING!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player9", null);
		yield break;
	}


	// .............
	// #14: player9

	void passage14_Init()
	{
		this.Passages[@"player9"] = new StoryPassage(@"player9", new string[]{ "player", }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text("That's a good boy!");
		yield return lineBreak();
		yield return text("Here's my Art Spy for you.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "dog9", null);
		yield break;
	}


	// .............
	// #15: dog9

	void passage15_Init()
	{
		this.Passages[@"dog9"] = new StoryPassage(@"dog9", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text("WOOF~");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player10", null);
		yield break;
	}


	// .............
	// #16: player10

	void passage16_Init()
	{
		this.Passages[@"player10"] = new StoryPassage(@"player10", new string[]{ "player", "end", }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text("What's this you've dug out of the ground?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text("Looks like some kind of foreign currency....");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "dog1", null);
		yield break;
	}


}