/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: dog2.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @dog2: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@dog2()
	{
		this.StartPassage = "dog1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: dog1

	void passage1_Init()
	{
		this.Passages[@"dog1"] = new StoryPassage(@"dog1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("FOG FRO OR WOW!");
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


	// .............
	// #2: player1

	void passage2_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("You sound like you're all jumbled up.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "dog2", null);
		yield break;
	}


	// .............
	// #3: dog2

	void passage3_Init()
	{
		this.Passages[@"dog2"] = new StoryPassage(@"dog2", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("BAA BRR FORK PORGY WOK");
		yield return lineBreak();
		yield return link("space", "player3", null);
		yield break;
	}


	// .............
	// #4: player3

	void passage4_Init()
	{
		this.Passages[@"player3"] = new StoryPassage(@"player3", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Hmm... Are you trying to imitate other animals?");
		yield return lineBreak();
		yield return link("space", "dog4", null);
		yield break;
	}


	// .............
	// #5: dog4

	void passage5_Init()
	{
		this.Passages[@"dog4"] = new StoryPassage(@"dog4", new string[]{ "end", }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("BEAK WHARF BURR FINK");
		yield return lineBreak();
		yield return link("space", "dog1", null);
		yield break;
	}


}