/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: baker_full_anagrams.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @baker_full_anagrams: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@baker_full_anagrams()
	{
		this.StartPassage = "baker1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: baker1

	void passage1_Init()
	{
		this.Passages[@"baker1"] = new StoryPassage(@"baker1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Eco mewl! You racy inlet look rather odd--you bus met new here!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: player1

	void passage2_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "baker2", null);
		yield break;
	}


	// .............
	// #3: baker2

	void passage3_Init()
	{
		this.Passages[@"baker2"] = new StoryPassage(@"baker2", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Anyways, eco mewl not two! Here, this art spy is on the use ho!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player2", null);
		yield break;
	}


	// .............
	// #4: player2

	void passage4_Init()
	{
		this.Passages[@"player2"] = new StoryPassage(@"player2", new string[]{ "end", "player", }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("-->You received a Pastry!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "baker3", null);
		yield break;
	}


	// .............
	// #5: baker3

	void passage5_Init()
	{
		this.Passages[@"baker3"] = new StoryPassage(@"baker3", new string[]{ "end", }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("I’m sorry, but I vegan thin ho to give you. I need to boat hearken batch of art spies! I hope you have a underway fold!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "baker3", null);
		yield break;
	}


}