/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: baker1.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @baker1: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@baker1()
	{
		this.StartPassage = "baker1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: baker1

	void passage1_Init()
	{
		this.Passages[@"baker1"] = new StoryPassage(@"baker1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("ECO MEWL! You RACY INLET look rather odd--you BUS MET new here!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


	// .............
	// #2: player1

	void passage2_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{ "player", }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "baker2", null);
		yield break;
	}


	// .............
	// #3: baker2

	void passage3_Init()
	{
		this.Passages[@"baker2"] = new StoryPassage(@"baker2", new string[]{ "end", }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Anyways, ECO MEWL NOT TWO! Here, this ~ART SPY~ is on the USE HO!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "baker3", null);
		yield break;
	}


	// .............
	// #4: baker3

	void passage4_Init()
	{
		this.Passages[@"baker3"] = new StoryPassage(@"baker3", new string[]{ "end", }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("I’m sorry, but I VEGAN THIN HO to give you. I need to BOAT HEARKEN batch of ~ART SPIES~! I hope you have an UNDERWAY FOLD!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "baker3", null);
		yield break;
	}


}