/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: dancer.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @dancer: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@dancer()
	{
		this.StartPassage = "dancer1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: dancer1

	void passage1_Init()
	{
		this.Passages[@"dancer1"] = new StoryPassage(@"dancer1", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Weeeeeeeeeeeee!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player1", null);
		yield break;
	}


	// .............
	// #2: dancer2

	void passage2_Init()
	{
		this.Passages[@"dancer2"] = new StoryPassage(@"dancer2", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("~Backpack~?? I DOWN KNOT about no ~Backpack~, but I HARE there's a BOX CHILI TOE at the EMU SUM. You should TICKET OUCH!");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "player2", null);
		yield break;
	}


	// .............
	// #3: player1

	void passage3_Init()
	{
		this.Passages[@"player1"] = new StoryPassage(@"player1", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("Hey! Have you seen my backpack around here?");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "dancer2", null);
		yield break;
	}


	// .............
	// #4: player2

	void passage4_Init()
	{
		this.Passages[@"player2"] = new StoryPassage(@"player2", new string[]{ "player", }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text("Wait... you can understand me???");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "dancer3", null);
		yield break;
	}


	// .............
	// #5: dancer3

	void passage5_Init()
	{
		this.Passages[@"dancer3"] = new StoryPassage(@"dancer3", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text("...");
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "dancer4", null);
		yield break;
	}


	// .............
	// #6: dancer4

	void passage6_Init()
	{
		this.Passages[@"dancer4"] = new StoryPassage(@"dancer4", new string[]{ "end", }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text("Weeeeeeeeeeeeeeeee!! ");
		using (Group("em", true)) {
			yield return text("NICE SNOUT CAN DING ICE FLOUR SOY");
		}
		yield return lineBreak();
		yield return lineBreak();
		yield return link("space", "dancer1", null);
		yield break;
	}


}